### ISSUE TITLE
Show or don't show how to add to homescreen depending on desktop/iOS/Android

### ISSUE THREAD

**Issue by clvlach** [jyasskin/sidewalk-obstruction-bingo#14]

**Comment by clvlach** [comment]
Actually for desktop instead of an add to homescreen option, show a print option. I can... make a PDF? Or is there a better way to get it to print?

**Comment by jyasskin** [comment]
Done in db30d6bdb820c80296f45e65858a3abd5826fb17. We might be able to improve the [instructions for Android](https://github.com/jyasskin/sidewalk-obstruction-bingo/blob/main/components/instructions-accordion.tsx#L35) since it'll pop up the prompt at the bottom of
![Add-to-home-screen prompt)](https://user-images.githubusercontent.com/83420/83218133-3e09a180-a122-11ea-9fb4-6d6b9790b59b.png)
on the first load.
